### ISSUE TITLE
Why is `hamburger-settings` needed?

### ISSUE THREAD

**Issue by antitoxic** [mrmlnc/hamburger-icon#2]
As per: https://github.com/mrmlnc/hamburger-icon/blob/master/README.md#how-to-use-1

User should call `.hamburger-settings(24px, 3px, 5px, #777, @timing-function: linear);` first and only then hamburger-generator();

Why?

The `sass-burger` makes it simpler by just calling a mixin a single time. Could the less version do the same?

**Comment by mrmlnc** [comment]
The problem is the scope of variables.

``` less
.menu-icon {
  .hamburger-generator(24px, 3px, 5px, #777, @timing-function: linear);
  // The variable is here, inside a block
  width: @hamburger-width;
}

// But the variable is not available outside that block
.class {
  width: @hamburger-width;
}
```

It turns out that the second mixin can't receive variables for the operation.

In the version under preprocessor Sass and Stylus are a variable that stores the configuration. The data for this variable are available for two-mixins. In Less of such a variable is not. Therefore, it is necessary to do so.

Any ideas how to fix it? :)
