### ISSUE TITLE
margin left and right for icon by default

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/hamburger-icon#4]
``` less
  .navbar-toggle {
    .hamburger-settings(24px, 3px, 5px, #777, @timing-function: linear);
    background-color: transparent;
    border: 0;
    cursor: pointer;
    outline: 0;
    padding: 0;
    height: 50px;
    width: 50px;

    & > .icon {
      .hamburger-generator();
      margin-left: auto;
      margin-right: auto;
    }

    &.-active > .icon {
      .hamburger-animation();
    }
  }
```
